<head>
    <?= $this->render('application/head/favicons'); ?>
    <?= $this->headTitle('Aplicação esqueleto')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta('', 'utf-8', 'charset')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink()
        ->prependStylesheet(
            $this->basePath('theme/dist/demo/default/base/style.bundle.css'),
            'all'
        )
        ->prependStylesheet(
            $this->basePath('theme/dist/vendors/base/vendors.bundle.css'),
            'all'
        )
        ->prependStylesheet(
            'https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700',
            'all'
        )
    ?>

    <?php
    $this->headScript()
        ->prependFile($this->basePath('theme/dist/demo/default/base/scripts.bundle.js'))
        ->prependFile($this->basePath('theme/dist/vendors/base/vendors.bundle.js'))
        ->prependFile('https://cdn.polyfill.io/v2/polyfill.min.js')
    ?>

</head>