<?php
$this->headScript()
    ->appendFile($this->manifestPath('dist/commons.js'))
    ->appendFile($this->manifestPath('dist/resumo.js'))
    ->prependScript('window.Vars = ' . $this->json($this->vars()) . ';')
?>
<div class="m-content">
    <div class="m-portlet m-portlet--mobile fadeInRight animated grid"
        id="grid-resumo">
        <div class="grid__tabela">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Resumo das operações
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <div class="m-form m--margin-bottom-30">
                    <div class="form-group m-form__group">
                        <?= $this->partial('grid/pesquisa', [
                            'sufixo' => 'Resumo',
                            'colunas' => [
                                ['coluna' => 'id', 'descricao' => '#', 'tipo' => 'number'],
                                ['coluna' => 'nome', 'descricao' => 'Nome', 'tipo' => 'string'],
                                ['coluna' => 'descricao', 'descricao' => 'Descrição', 'tipo' => 'string'],
                                ['coluna' => 'preco', 'descricao' => 'Valor', 'tipo' => 'number'],
                            ]
                        ]); ?>
                    </div>
                </div>
            <div class="m_datatable m-datatable m-datatable--default m-datatable--loaded">
                <?= $this->render('resumo/index/grid') ?>
                <?= $this->render('grid/paginacao') ?>
            </div>
        </div>
    </div>
</div>

