<li
    title="Meu usuário"
    class="m-nav__item m-topbar__user-profile m-topbar__user-profile--img  m-dropdown m-dropdown--medium m-dropdown--arrow m-dropdown--header-bg-fill m-dropdown--align-right m-dropdown--mobile-full-width m-dropdown--skin-light"
    data-dropdown-toggle="click">
    <a href="#" class="m-nav__link m-dropdown__toggle">
        <div class="m-widget4__img m-widget4__img--logo m-card-user m-card-user--sm">
                <div class="m-card-user__pic m-topbar__userpic">
                    <div class="m-card-user__no-photo
                        m--bg-fill-info"
                        style="height:35px; width:35px">
                        <span>C</span>
                    </div>
                </div>
        </div>
        <span class="m-topbar__username m--hide">
            Convidado
        </span>
    </a>
    <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
        <div class="m-dropdown__inner">
            <div
                class="m-dropdown__header m--align-center"
                style="background: url(/theme/src/media/app/img/misc/quick_actions_bg.jpg); background-size: cover;">
                <div class="m-card-user m-card-user--skin-dark">
                    <div class="m-card-user__pic">
                        <div class="m-widget4__img m-widget4__img--logo m-card-user m-card-user--bg">
                            <div class="m-card-user m-card-user--bg">
                                <div class="m-card-user__pic">
                                    <div class="m-card-user__no-photo m--bg-fill-info">
                                        <span style="font-size:30px">C</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-card-user__details">
                        <span class="m-card-user__name m--font-weight-500">
                            Convidado
                        </span>
                        <a href="#" class="m-card-user__email m--font-weight-300 m-link" style="word-break: break-all;"></a>
                    </div>
                </div>
            </div>
            <div class="m-dropdown__body">
                <div class="m-dropdown__content">
                    <ul class="m-nav m-nav--skin-light">
                        <li class="m-nav__item">
                            <a
                                href="/logout"
                                class="btn m-btn--pill btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">
                                Sair
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>