<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <div class="m-content">
        <h1>404</h1>
        <h2><?= $this->message ?></h2>
        <?php if ($this->reason) :
            switch ($this->reason) {
                case Zend\Mvc\Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
                    $reasonMessage = 'A controller solicitada não pode disparar a requisição.';
                    break;
                case Zend\Mvc\Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
                    $reasonMessage = 'O middleware não pode disparar a requisição.';
                    break;
                case Zend\Mvc\Application::ERROR_CONTROLLER_NOT_FOUND:
                    $reasonMessage = 'A controller solicitada não foi mapeada para uma classe existente.';
                    break;
                case Zend\Mvc\Application::ERROR_CONTROLLER_INVALID:
                    $reasonMessage = 'Controller inválida.';
                    break;
                case Zend\Mvc\Application::ERROR_ROUTER_NO_MATCH:
                    $reasonMessage = 'A url solicitada não foi encontrada.';
                    break;
                default:
                    $reasonMessage = 'Não foi possível determinar o motivo essa página 404 foi gerada.';
                    break;
            }
        ?>
        <p><?= $reasonMessage ?></p>
        <?php endif ?>
        <?php if ($this->controller) : ?>
        <dl>
            <dt>Controller:</dt>
            <dd>
                <?= $this->escapeHtml($this->controller) ?>
                <?php
                if ($this->controller_class && $this->controller_class != $this->controller) {
                    printf('(resolves to %s)', $this->escapeHtml($this->controller_class));
                }
                ?>
            </dd>
        </dl>
        <?php endif ?>
        <?= $this->render('error/exception') ?>
    </div>
</div>