variables:
  DEV: ubuntu@54.232.248.199
  PROD: ubuntu@52.67.21.31

test:php:
  stage: test
  image: tetraweb/php:7.1
  cache:
    paths:
    - vendor/
  before_script:
    - docker-php-ext-enable xdebug
    - apt-get update; apt-get install unzip
    - docker-php-ext-install pdo_mysql
    - composer install
    - echo 'memory_limit=-1' >> /usr/local/etc/php/conf.d/php.ini
    - echo 'short_open_tag=0' >> /usr/local/etc/php/conf.d/php.ini
  script: composer test -- --coverage-text --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

deploy:prod:
  image: tetraweb/php:7.1
  before_script:
    - apt-get update; apt-get install unzip
    - composer install
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$DEPLOY_PRIVATE_KEY" | base64 --decode)
  stage: deploy
  cache:
    paths:
    - node_modules/
    - vendor/
  script:
    - rsync -av ./ $PROD:/var/www/gitlab/master/apiconciliadora/
  environment:
    name: production
    url: http://apiconciliadora.maxscalla.com.br
  only:
    - master
