<div class="m-login__forget-password">
    <div class="m-login__head">
        <h3 class="m-login__title">
            Esqueceu sua senha ?
        </h3>
        <div class="m-login__desc">
            Insira seu email para recuperar sua senha
        </div>
    </div>
    <form class="m-login__form m-form" id="form-esqueci-minha-senha" action="">
        <div class="form-group m-form__group">
            <input
                class="form-control m-input"
                type="text"
                placeholder="Email"
                name="email"
                id="m_email"
                autocomplete="off">
        </div>
        <div class="m-login__form-action">
            <button
                id="m_login_forget_password_submit"
                class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">
                Solicitar
            </button>
            <button
                id="m_login_forget_password_cancel"
                class="btn btn-outline-focus m-btn m-btn--pill m-btn--custom">
                Cancelar
            </button>
        </div>
    </form>
</div>