<div class="m-login__signup">
    <div class="m-login__head">
        <h3 class="m-login__title">
            Inscreva-se
        </h3>
        <div class="m-login__desc">
            Insira seus dados para criar sua conta:
        </div>
    </div>
    <form class="m-login__form m-form" action="#">
        <div class="form-group m-form__group">
            <input
                type="text"
                name="nome"
                class="form-control m-input"
                placeholder="Nome">
        </div>
        <div class="form-group m-form__group">
            <input
                type="text"
                name="email"
                class="form-control m-input"
                placeholder="Email">
        </div>
        <div class="form-group m-form__group">
            <input
                type="password"
                name="password"
                class="form-control m-input"
                placeholder="Senha">
        </div>
        <div class="form-group m-form__group">
            <input
                type="password"
                name="rpassword"
                class="form-control m-input m-login__form-input--last"
                placeholder="Repita sua senha" >
        </div>
        <div class="row form-group m-form__group m-login__form-sub">
            <div class="col m--align-left">
                <label class="m-checkbox m-checkbox--focus">
                    <input type="checkbox" name="agree">
                    Aceito os
                    <a href="#" class="m-link m-link--focus">
                        termos e condições
                    </a>
                    .
                    <span></span>
                </label>
                <span class="m-form__help"></span>
            </div>
        </div>
        <div class="m-login__form-action">
            <button
                id="m_login_signup_submit"
                class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">
                Cadastrar
            </button>
            <button
                id="m_login_signup_cancel"
                class="btn btn-outline-focus  m-btn m-btn--pill m-btn--custom">
                Cancelar
            </button>
        </div>
    </form>
</div>