<div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions m-form__actions">
        <div class="row">
            <div class="col-lg-9 ml-lg-auto">
                <button type="submit" class="btn btn-primary">
                    Enviar
                </button>
                <button type="reset" class="btn btn-secondary voltar esq">
                    Cancelar
                </button>
            </div>
        </div>
    </div>
</div>
