<div class="form-group m-form__group row">
    <label class="col-form-label col-lg-3 col-sm-12" for="descricao-<?= $this->prefixo ?>">
        Descrição:
    </label>
    <div class="col-lg-6 col-md-9 col-sm-12">
        <input
            type="text"
            name="descricao"
            id="descricao-<?= $this->prefixo ?>"
            class="form-control m-input"
            maxlength="40"
            placeholder="Digite aqui..."
            required>
    </div>
</div>