<div class="form-group m-form__group row">
    <label class="col-form-label col-lg-3 col-sm-12" for="ativo-<?= $this->prefixo ?>-sim">
            Ativo:
        <span class="m--font-danger">*</span>
    </label>
    <div class="col-lg-4 col-md-9 col-sm-12">
        <div class="m-radio-list">
            <label class="m-radio">
                <input
                    type="radio"
                    name="ativo"
                    value="1"
                    id="ativo-<?= $this->prefixo ?>-sim"
                    checked="checked"
                    required>
                Sim
                <span></span>
            </label>
            <label class="m-radio">
                <input
                    type="radio"
                    name="ativo"
                    value="0"
                    id="ativo-<?= $this->prefixo ?>-nao">
                Não
                <span></span>
            </label>
        </div>
    </div>
</div>