<?php

$appleTouchIcon = [57, 60, 72, 76, 114, 120, 144, 152, 180];
$relIcon = [16, 32, 96, 192];

$this->headMeta()
    ->appendName(
        'msapplication-config',
        $this->basePath("/img/favicon/browserconfig.xml")
    )
    ->appendName(
        'msapplication-TileImage',
        $this->basePath("/img/favicon/ms-icon-144x144.png")
    )
    ->appendName('theme-color', '#ffffff')
    ->appendName('msapplication-TileColor', '#ffffff');

$this->headLink([
    'rel' => 'manifest',
    'href' => $this->basePath("/img/favicon/manifest.json"),
]);

foreach ($relIcon as $resolucao) {
    $this->headLink([
        'rel' => 'icon',
        'type' => 'image/png',
        'sizes' => $resolucao . 'x' . $resolucao,
        'href' => $this->basePath("/img/favicon/favicon-{$resolucao}x{$resolucao}.png"),
    ]);
}

foreach ($appleTouchIcon as $resolucao) {
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'sizes' => $resolucao . 'x' . $resolucao,
        'href' => $this->basePath("/img/favicon/apple-icon-{$resolucao}x{$resolucao}.png"),
    ]);
}
