<div class="modal fade" id="modal-padrao" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-padrao-title"></h5>
                <button type="button" class="close" id="modal-close" style="cursor: pointer;" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body" id="modal-padrao-body"></div>
            <div class="modal-footer" id="modal-padrao-footer" style="display: none;"></div>
        </div>
    </div>
</div>