<div class="paginacao m-datatable__pager m-datatable--paging-loaded clearfix">
    <script type="text/template">
        <ul class="m-datatable__pager-nav">
            <li class="paginacao--anterior {{#disableAnterior}}disabled{{/disableAnterior}}">
                <a class="m-datatable__pager-link m-datatable__pager-link--prev {{#disableProximo}}m-datatable__pager-link--disabled{{/disableProximo}}">
                    <i class="la la-angle-left"></i>
                </a>
            </li>
            {{#paginas}}
                <li>
                    <a class="m-datatable__pager-link m-datatable__pager-link-number {{#active}}m-datatable__pager-link--active{{/active}} paginacao--pagina">
                        {{pagina}}
                    </a>
                </li>
            {{/paginas}}
            <li class="paginacao--proximo {{#disableProximo}}disabled{{/disableProximo}}">
                <a class="m-datatable__pager-link m-datatable__pager-link--next {{#disableProximo}}m-datatable__pager-link--disabled{{/disableProximo}}">
                    <i class="la la-angle-right"></i>
                </a>
            </li>
        </ul>
        {{#totais}}
            <div class="m-datatable__pager-info">
                <span class="m-datatable__pager-detail">
                    Mostrando página {{pagina}} de {{quantidadePaginas}} (Filtrado de {{totalRegistros}} registros).
                </span>
                <span class="grid__itens-selecionados">{{mensagemItensSelecionados}}</span>
            </div>
        {{/totais}}
    </script>
</div>