<form class="form-inline grid__filtro" id="formulario<?= $this->sufixo ?>">
    <?php if ($this->quantidade !== false) : ?>
        <select name="quantidade" class="form-control">
            <option value="10">10</option>
            <option value="15">15</option>
            <option value="20">20</option>
            <option value="40">40</option>
            <option value="100">100</option>
        </select>
    <?php endif; ?>
    <select name="coluna" class="form-control" id="coluna<?= $this->sufixo ?>">
        <option value="" data-tipo="string">
            Todas
        </option>
        <?php foreach ($this->colunas as $value) : ?>
            <option value="<?= $value['coluna'] ?>" data-tipo="<?= $value['tipo'] ?>">
                <?= $value['descricao'] ?>
            </option>
        <?php endforeach; ?>
    </select>
    <select name="opcao" class="form-control" id="opcao<?= $this->sufixo ?>">
        <option value="contendo" data-tipo="string" selected="seleted">
            Contendo
        </option>
        <option value="iniciando" data-tipo="string">
            Iniciando
        </option>
        <option value="=" data-tipo="number" style="display: none">
            = Igual
        </option>
        <option value="<" data-tipo="number" style="display: none">
            < Menor
        </option>
        <option value="<=" data-tipo="number" style="display: none">
            ≦ Menor ou igual
        </option>
        <option value=">" data-tipo="number" style="display: none">
            >Maior
        </option>
        <option value=">=" data-tipo="number" style="display: none">
            ≧ Maior ou igual
        </option>
    </select>
    <input
        type="search"
        name="valor"
        class="form-control"
        id="valor<?= $this->sufixo ?>"
        step="any"
        placeholder="Digite aqui..."
        required="required" />
    <button type="submit" class="btn btn-success" form="formulario<?= $this->sufixo ?>">
        <i class="fa fa-search"></i>
    </button>
    <button type="reset" class="btn btn-info">
        <i class="fa fa-refresh"></i>
        Limpar
    </button>
</form>
