<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark">
    <div
        id="m_ver_menu"
        class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark"
        data-menu-vertical="true"
        data-menu-scrollable="false" data-menu-dropdown-timeout="500">
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">

            <li class="m-menu__item" aria-haspopup="true">
                <a href="<?= $this->url('home') ?>" class="m-menu__link">
                    <i class="m-menu__link-icon la la-home" title="Home"></i>
                    <span class="m-menu__link-text">
                        Home
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true">
                <a href="<?= $this->url('resumo') ?>" class="m-menu__link">
                    <i class="m-menu__link-icon flaticon-clipboard" title="Resumo"></i>
                    <span class="m-menu__link-text">
                        Resumo
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true">
                <a href="<?= $this->url('comprovante') ?>" class="m-menu__link">
                    <i class="m-menu__link-icon 	la la-newspaper-o" title="Resumo"></i>
                    <span class="m-menu__link-text">
                        Comprovante
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>
