<div class="m-login__signin">
    <div class="m-login__head">
        <h3 class="m-login__title">
            Entrar
        </h3>
    </div>
    <form id="form-login" class="m-login__form m-form">
        <?php if ($this->message) : ?>
            <div class="m-alert m-alert--outline alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                <span><?= $this->message ?></span>
            </div>
        <?php endif; ?>
        <div class="form-group m-form__group">
            <input
                type="email"
                name="email"
                class="form-control m-input"
                placeholder="Email"
                tabindex="1"
                required>
        </div>
        <div class="form-group m-form__group">
            <input
                type="password"
                name="senha"
                class="form-control m-input m-login__form-input--last"
                placeholder="Senha"
                tabindex="2"
                required>
        </div>
        <div class="row m-login__form-sub">
            <?php if ($this->esqueceuSuaSenha) : ?>
                <div class="col m--align-right">
                    <a
                        href="javascript:;"
                        id="m_login_forget_password"
                        class="m-link">
                        Esqueceu sua senha?
                    </a>
                </div>
            <?php endif; ?>
        </div>
        <div class="m-login__form-action">
            <button
                type="submit"
                tabindex="4"
                class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">
                Entrar
            </button>
        </div>
    </form>
</div>