<div class="m-portlet m-portlet--full-height">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Tasks
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="nav nav-pills nav-pills--brand m-nav-pills--align-right m-nav-pills--btn-pill m-nav-pills--btn-sm" role="tablist">
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_widget2_tab1_content" role="tab">
                    Today
                    </a>
                </li>
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_widget2_tab2_content1" role="tab">
                    Week
                    </a>
                </li>
                <li class="nav-item m-tabs__item">
                    <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_widget2_tab3_content1" role="tab">
                    Month
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="m_widget2_tab1_content">
                <div class="m-widget2">
                    <div class="m-widget2__item m-widget2__item--primary">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Make Metronic Great  Again.Lorem Ipsum Amet
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By Bob
                            </a>
                            </span>
                        </div>
                    </div>
                    <div class="m-widget2__item m-widget2__item--warning">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Prepare Docs For Metting On Monday
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By Sean
                            </a>
                            </span>
                        </div>
                    </div>
                    <div class="m-widget2__item m-widget2__item--brand">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Make Widgets Great Again.Estudiat Communy Elit
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By Aziko
                            </a>
                            </span>
                        </div>
                    </div>
                    <div class="m-widget2__item m-widget2__item--success">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Make Metronic Great Again.Lorem Ipsum
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By James
                            </a>
                            </span>
                        </div>
                    </div>
                    <div class="m-widget2__item m-widget2__item--danger">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Completa Financial Report For Emirates Airlines
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By Bob
                            </a>
                            </span>
                        </div>
                    </div>
                    <div class="m-widget2__item m-widget2__item--info">
                        <div class="m-widget2__checkbox">
                            <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                            <input type="checkbox">
                            <span></span>
                            </label>
                        </div>
                        <div class="m-widget2__desc">
                            <span class="m-widget2__text">
                            Completa Financial Report For Emirates Airlines
                            </span><br>
                            <span class="m-widget2__user-name">
                            <a href="#" class="m-widget2__link">
                            By Sean
                            </a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="m_widget2_tab2_content">

            </div>
            <div class="tab-pane" id="m_widget2_tab3_content">

            </div>
        </div>
    </div>
</div>